In [2]:
import numpy as np


In [50]:
A = [[5,4,1],[5,5,0], [0,0,5], [1,0,4]]
P,D,Q = np.linalg.svd(A)

In [66]:
P.shape, D.shape, Q.shape

((4, 4), (3,), (3, 3))

In [54]:
smat = np.zeros((P.shape[1], Q.shape[0]))

smat[:Q.shape[0], :Q.shape[0]] = np.diag(D)
smat

array([[9.6438109 , 0.        , 0.        ],
       [0.        , 6.36389089, 0.        ],
       [0.        , 0.        , 0.70555232],
       [0.        , 0.        , 0.        ]])

In [65]:
first_column_P = P[:, 0]
first_column_P.shape, smat[:,0].shape
(first_column_P*smat[0,0])*Q[0]

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [53]:


np.round(P@smat, 2).real

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [15]:
rng = np.random.default_rng()

a = rng.normal(size=(9, 6)) + 1j*rng.normal(size=(9, 6))

b = rng.normal(size=(2, 7, 8, 3)) + 1j*rng.normal(size=(2, 7, 8, 3))

U, S, Vh = np.linalg.svd(a, full_matrices=True)

U.shape, S.shape, Vh.shape

((9, 9), (6,), (6, 6))

Co się stanie, gdy będą tylko dwa filmy z jednego gatunku:

In [24]:
A = [[5,4,1],[5,5,0]]
P,D,Q = np.linalg.svd(A)
P,D,Q

(array([[-0.67507785, -0.7377465 ],
        [-0.7377465 ,  0.67507785]]),
 array([9.54868724, 0.90695756]),
 array([[-0.73980031, -0.66910181, -0.0706985 ],
        [-0.34548831,  0.4679417 , -0.81343001],
        [-0.57735027,  0.57735027,  0.57735027]]))

Co, gdy będą dwa różne filmy

In [25]:
A = [[5,4,1], [0,0,5]]
P,D,Q = np.linalg.svd(A)
P,D,Q

(array([[-0.96486637, -0.26274111],
        [-0.26274111,  0.96486637]]),
 array([6.5849481 , 4.86193979]),
 array([[-7.32630199e-01, -5.86104160e-01, -3.46027318e-01],
        [-2.70201940e-01, -2.16161552e-01,  9.38224437e-01],
        [-6.24695048e-01,  7.80868809e-01,  2.42861287e-16]]))

In [36]:
smat = np.zeros((P.shape[1], Q.shape[0]))

dimension = min(P.shape[1], Q.shape[0])
smat[:dimension, :dimension] = np.diag(D)
# = np.diag(D)
P@smat

array([[-6.35359495, -1.27743147,  0.        ],
       [-1.73013659,  4.69112219,  0.        ]])

In [30]:
Q[2:]

array([[-6.24695048e-01,  7.80868809e-01,  2.42861287e-16]])

Co gdy będą trzy filmy tego samego gatunku

In [38]:
A = [[5,4,1],[5,5,0], [4,5,1]]
P,D,Q = np.linalg.svd(A)
np.round(P,2),np.round(D,2),np.round(Q,2)

(array([[-0.56,  0.71,  0.43],
        [-0.61,  0.  , -0.79],
        [-0.56, -0.71,  0.43]]),
 array([11.5 ,  1.  ,  0.87]),
 array([[-0.7 , -0.7 , -0.1 ],
        [ 0.71, -0.71, -0.  ],
        [-0.07, -0.07,  1.  ]]))

Podzielmy przez pierwszy wektor z macierzy P, czyli [-0.56, -0.61, -0.56]

In [49]:
np.round((A@Q[0])/[-0.56,-0.61,-0.56],2)

array([11.48, 11.54, 11.48])

Otrzymujemy 11.5, czyli pierwszą wartość osobliwą z macierzy D

In [39]:
np.round(P@np.diag(D),2)

array([[-6.43,  0.71,  0.38],
       [-7.04,  0.  , -0.69],
       [-6.43, -0.71,  0.38]])